# Numpy Review

In this review, we are going to refresh our memories about the Numpy package. Numpy (numerical Python) is the basic engine that turns Python into a tool for data analysis. Anything "data sciency" that you do in Python will rely on Numpy at some point, either explicitly (when calling Numpy fuctions directly), or implicitly (when, e.g., using Pandas).

The point of Numpy is do make working with data in Python easier and faster. Here, we going to remind ourselves of basic Numpy functionality.

## Python lists

First, let's look at a basic Python list:

In [2]:
a_list = [2, 4, 6, 8]

---

Just to warm up, let's get some items from our list via *indexing*:

Get the first number from the list (the "zeroith" number in Pythonese):

In [3]:
a_list[0]

2

Get the last two numbers:

In [6]:
a_list[2:]

[6, 8]

---

Now let's make a *nested* Python list:

In [7]:
a_nested_list = [[2, 4], [3, -1], [-2, 1]]

Remember that a Python list can hold data of different types, lengths, etc., but this list is special; it is a *list of lists* all of the same length.

Let's have a look:

In [8]:
print(a_nested_list)

[[2, 4], [3, -1], [-2, 1]]


How would we get the first entry in the second list? 

We could do it in two steps... first, get the second list:

In [9]:
sec_list = a_nested_list[1]

And then get the first entry:

In [10]:
my_num = sec_list[0]
print(my_num)

3


Conveniently, we can just do this in one go:

In [11]:
my_num = a_nested_list[1][0]
print(my_num)

3


This does the same thing without having to invoke the intermediate variable `sec_list`. 

While this list-of-lists construct might seem a little abstract, there is actually a nice way to wrap our heads around it, which is to think of it as a *matrix*.

> Unfortunately, no one can be told what the Matrix is. You have to see it for yourself. *- Morpheus*

Here is an example of a matrix:

![A matrix](./images/mailboxes.png)

A ***matrix*** is a 2 dimensional (2D) arrangement of things and, for our purposes, the things are data of one form or another (numbers, strings, timestamps, etc.).

These mailboxes are numbered sequentially, because there are other mailboxes in other matrices and that's just how the USPS rolls. But, notice that, for *this* matrix of mailboxes, there is another way in which we could uniquely refer to each mailbox. Specifically, we could uniquely specify each mailbox by the *row* it is in and the *column* it is in.

For example, the open mailbox with the key in the door is in the 2nd row and the 4th column or, in terms of Python indexes, the mailbox is at location [1, 3]. 

So, we can think of matrix as an arrangement of data that has a built in ***spatial coordinate system*** used to refer to the items of data.

Here's another Python list of lists:

In [12]:
another_nested_list = [[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5],
                       [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]

As far as Python is concerned, this is just a list that happens to contain 5 lists, each of length 3:

In [14]:
print(f'Another nested Python list: {another_nested_list}')

Another nested Python list: [[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5], [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]


But it makes sense for our human brains to think about it as a 2D arrangement of data, like this: 

| row # | Col # | | | | |
| ---- | ---- | ---- | ---- | ---- | ---- |
|   | 0 | 1 | 2 | 3 |  4 | 5 |
| 0 | 3.3 | 1.2 | 4.8 | 1.5 |  5.9 | 9.0 |
| 1 | 2.3 | 7.8 | 2.2 | 7.5 |  1.6 | 8.1 |
| 2 | 2.2 | 8.7 | 6.5 | 9.5 |  7.7 | 5.2 |

Now we can think of the Python indexes used to access the data as spatial ***row*** and ***column*** coordinates. For example:

In [15]:
another_nested_list[2][1]

2.2

fetches the data value in the second row (row index 1) and the third column (column index 2). 

Even though, in Python terms, `another_nested_list` is just a list of lists that all happen to be of the same length, it's very helpful for us to map data like this onto a matrix and think of the indexes as coordinates.

## Numpy

Numpy is a big and powerful package, but you can think of it's most basic function as making this matrix-like way of thinking about data explicit, as opposed to just a cute way of thinking about lists of lists.

To use numpy, we first import it. Traditionally, it is imported under the name "`np`".

In [2]:
import numpy as np

Now we can convert our latest nested list into a numpy matrix using numpy's `array()` function:

In [17]:
our_numpy_matrix = np.array(another_nested_list)

Let's look at our new matrix!

In [18]:
print(our_numpy_matrix)

[[3.3 2.3 2.2]
 [1.2 7.8 8.7]
 [4.8 2.2 6.5]
 [1.5 7.5 9.5]
 [5.9 1.6 7.7]]


And compare it to the Python list from which we created it.

In [19]:
print(another_nested_list)

[[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5], [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]


We can see that the numpy version has made the spatial row x column arrangement explicit.

Now, getting data values is easy peasy, we just index into our new matrix with row and column coordinates of a desired value:

In [20]:
our_numpy_matrix[2,0] # get the data at the third row and first column

4.8

Let's see what data type our new matrix is, according to Python:

In [21]:
type(our_numpy_matrix)

numpy.ndarray

So our new matrix is a Python object made by numpy of type "ndarray", which is short for "N-dimesional array" – we'll unpack this in a bit.

But our object contains other objects (in that Pythonic way), so let's see what they are:

In [22]:
type(our_numpy_matrix[2,0])

numpy.float64

So they are floating point numbers, also defined in numpy, that presumably have a few more bells and whistles that regular Python floats (the 64 at the end means that 64 bits are used to store each number; this is the number's *precision*.

You may have noticed that our new matrix is a little different than the way we laid out our numbers in the table above. There, we made each sub-list into a column, whereas the `array` function seems to have made each list into a row.

Fear not! Numpy objects, like all Python objects "know" how to do things; they have *methods*. The need to turn the rows into columns and vice versa is very common – it is called *transposing* a matrix – so numpy arrays have a *transpose* method `T`.

In [23]:
transposed_matrix = our_numpy_matrix.T
print(transposed_matrix)

[[3.3 1.2 4.8 1.5 5.9]
 [2.3 7.8 2.2 7.5 1.6]
 [2.2 8.7 6.5 9.5 7.7]]


Notice that the value 4.8 used to be in the third row of the first column, but now it's coordinates have been flipped:

In [24]:
transposed_matrix[0,2] # new location of 4.8

4.8

In [25]:
transposed_matrix[2,0] # value at the old location

2.2

---

In the code cell below, make a Python list of lists, create a numpy matrix from it, transpose it, and access 3 of it's values.

In [33]:
# python list
python_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# numpy matrix
np_matrix = np.array(python_list)

# transposed matrix
transposed_np_matrix = np_matrix.T


print(transposed_np_matrix)
print(transposed_np_matrix[0,1], transposed_np_matrix[1,0], transposed_np_matrix[2,2])

[[1 4 7]
 [2 5 8]
 [3 6 9]]
4 2 9


### Numpy arrays 

So far, we've been talking about our data above as a "matrix", yet we used the `array()` function to make it, and Python tells us that our matrix is an `ndarray` – what's going on?

#### Types of arrays

"Array" is a general term for a structured collection of data, and can have any number of dimensions (hence "ndarray" for "N-dimensional array"). Here's an (empty) 3 dimensional array:

![A 3D array](images/array.png)

If this array were named "phred", we would index it just like above, but with an extra index – the coordinate specifying the location along the third dimension. So `phred[5, 5, 3]` would specify the bottom right location just peeking out on the fourth – what? – "page" of the array.

Though arrays can have any number of dimensions, lower-dimensional arrays are common and get their own special names.

A "matrix" is an array of 2 dimensions. As you already know, a matrix is a universal format for data and is preferably in "tidy" format, where each row is an observation and each column is a variable.

A "vector" is a list of numbers, so named because a simple list of numbers is used in math (linear algebra) and physics to specify vectors (such as force). Vectors can be 

* "row vectors" - a matrix with a single row
* "column vectors" - a matrix with a single column
* a list of numbers with only a single dimension, like a Python list

Finally, in this lingo, a single number is referred to as a "scaler" (because multiplying a vector by a number scales the length of the vector without changing its direction).

---

In the cell below, make a Python list or tuple containing the x and y coordinates of a point (any point you like – I'm a big fan of x=3, y=1 personally). On a piece of paper or a drawing program or whatever, plot the point in an x,y coordinate system, and draw an arrow – a vector! – from the origin to your point.

In [34]:
v = (3, 1)

Now convert your Python object into a numpy array.

In [35]:
va = np.array(v)

Get the shape of your new vector using the `shape` method (used just like the `T` method above).

In [36]:
va.shape

(2,)

Multiply your vector by 2 (if your vector is named "Velma", then you would literally do `Velma * 2`).

In [37]:
va*2

array([6, 2])

Plot your new vector and confirm that the multiplication *scaled* the original vector up by a factor of 2 without changing its direction!

---

We've just illustrated an awesome thing about numpy ndarrays: if we want to do simple operations on an entire array, we don't need to do it element-by-element, we just do it on the entire array in one go! Despite operating on arrays in general, this property is referred to as "*vectorization*" of operations.

#### Making numpy arrays 

##### arrays from lists or tuples

We've already seen that we can make numpy arrays from Python lists. Like this:

In [38]:
print(f'A python list: {a_list}')

a_numpy_thing = np.array((a_list))

print(f'A numpy thing: {a_numpy_thing}')

A python list: [2, 4, 6, 8]
A numpy thing: [2 4 6 8]


Or this:

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

---

In the cell below, confirm that you can make a numpy array from a Python tuple.

In [42]:
my_tup = (2, 4, 6, 8, 10)

tup_to_numpy = np.array(my_tup)

print(tup_to_numpy)

[ 2  4  6  8 10]


##### ones and zeros

If we're creating or reading in data from a source other than a Python list or tuple, we need a place to put it. To make new arrays to hold stuff, we first create an array filled with something. Most of the time, it doesn't matter what we fill it with. We commonly fill new arrays with ones or zeros.

In [43]:
a_vec = np.ones((3,2))
print(f'an array of ones:\n {a_vec}')

an array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


---

In the cell below, make an array of zeros.

In [44]:
vec_zeros = np.zeros((4,3))
print(f'an array of zeros:\n {vec_zeros}')

an array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

##### Any number 

We can also initialize an array to any value we want.

In [45]:
the_answer = np.full((3,3), 42)
print(f'Every cell has the answer!:\n {the_answer}')

Every cell has the answer!:
 [[42 42 42]
 [42 42 42]
 [42 42 42]]


---

In the cell below, get the same result as above (a 3x3 array of 42s) using 1) `np.ones` and 2) `np.zeros`. 
(Hint: take advantage of vectorization using `*` and `+`)

In [53]:
# using np.ones
np_ones = np.ones((3,3))
ones_w_ans = 42 * np_ones
print(f"This is the 3x3 array using np.ones:\n {ones_w_ans}\n")

# using np.zeros
np_zeros = np.zeros((3,3))
zeros_w_ans = 42 + np_zeros
print(f"This is the 3x3 array using np.zeros:\n {zeros_w_ans}")

This is the 3x3 array using np.ones:
 [[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]

This is the 3x3 array using np.zeros:
 [[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


##### random numbers

In data science, we often add random noise to simulations in order to capture the random variability present in the universe and the data we get from it. We can do this using any number of functions in `np.random`. For example

In [3]:
my_noise = np.random.randn(4,4)
print(f'C\'mon feel the noise! \n {my_noise}')

C'mon feel the noise! 
 [[ 0.02202286  0.32436108 -1.89779356 -0.4232918 ]
 [ 1.67314474 -1.26653071  1.35599227 -0.31438775]
 [ 0.32935376  0.6655817  -0.11362564  1.25031778]
 [-1.10465767 -0.6998781   1.05124346  0.34262669]]


Which made normally distributed (Gaussian) noise. 

We can also make noise that is uniformly distributed:

In [55]:
unif_noise = np.random.rand(4,4)
print(f'Moar noise! \n {unif_noise}')

Moar noise! 
 [[0.87674427 0.67818472 0.25224563 0.97415678]
 [0.56292552 0.57478279 0.04636912 0.5382652 ]
 [0.15153849 0.59096397 0.14601231 0.67284582]
 [0.52466016 0.70012633 0.78894695 0.71395075]]


Or we can make random integers:

In [56]:
int_noise = np.random.randint(1, 11, (4,4))
print(f'Random integers! \n {int_noise}')

Random integers! 
 [[ 6  6  3  1]
 [ 9  4  9  1]
 [ 6  7 10  9]
 [ 5  3  3  3]]


##### the identity matrix

Finally, we can make an "identity matrix", a matrix with 1s running down the diagonal. It's useful for linear algebra applications, and is included there only for completeness.

In [57]:
aye = np.eye(4,4)
print(f'Aye aye Cap\'n! \n {aye}')

Aye aye Cap'n! 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---

In the cell below, make a 6x6 array containing random integers from -10 to 10.

In [58]:
rand_ints = np.random.randint(-10, 10, (6,6))
rand_ints

array([[ -5,  -1,   0,  -5,   6,   3],
       [ -7,   2,  -3,   8,  -4,  -5],
       [ -4,  -3,  -2,  -8,  -7,  -9],
       [ -5,   6,   0,  -4,  -4,   8],
       [ -2,  -3,   1,  -4,  -5, -10],
       [ -1,   1,  -3,  -8, -10,  -7]])

#### "vectorized" operations 

As mentioned above, most of the common Python operators become *vectorized* in numpy, which means that we can to the same thing to every element of our arrays in one go.

let's add 10 to all our Gaussian random numbers from above.

In [59]:
amp_noise = my_noise + 11
amp_noise

array([[11.7699664 , 11.8555334 , 11.39706116, 10.73964336],
       [10.48496057,  9.87526579,  9.27187225, 12.16831498],
       [10.39742237, 13.09707017, 11.01657564, 11.30294492],
       [ 9.17926386,  9.85198568, 11.71877496, 11.68474265]])

Let's see which ones go to 11!

In [60]:
amp_noise >= 11

array([[ True,  True,  True, False],
       [False, False, False,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True]])

If arrays are the same size, we can do element-by-element things easily.

Which elements of the Gaussian noise are greater than the corresponding elements of the uniform noise?

In [61]:
my_noise > unif_noise

array([[False,  True,  True, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False, False, False]])

Add our Gaussian and integer noise element-by-element:

In [62]:
my_noise + int_noise

array([[ 6.7699664 ,  6.8555334 ,  3.39706116,  0.73964336],
       [ 8.48496057,  2.87526579,  7.27187225,  2.16831498],
       [ 5.39742237,  9.09707017, 10.01657564,  9.30294492],
       [ 3.17926386,  1.85198568,  3.71877496,  3.68474265]])

Divide our identity matrix by our integer noise – everything off the main diagonal should be zero...

In [63]:
aye / int_noise

array([[0.16666667, 0.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.        , 0.        ],
       [0.        , 0.        , 0.1       , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333]])

---

In the cell below, make a 10x5 matrix containing normally distributed random numbers with a mean of about 100 and a standard deviation of about 15 using vectorized operations.

In [68]:
new_matrix = np.random.rand(10,5)
mean = 100
sd = 15
# random numbers adjusted to mean of 100 and standard deviation of 15
(new_matrix * sd) + mean

array([[102.41051174, 104.09868154, 102.82254859, 114.33601792,
        104.22367356],
       [112.72532246, 106.7557182 , 102.95928155, 113.62248494,
        110.03723998],
       [108.05527795, 113.14110831, 106.43977627, 111.9873107 ,
        102.18692442],
       [110.64479493, 106.57405438, 113.56511951, 101.28494487,
        104.89176626],
       [104.04810814, 108.85124866, 106.26069472, 102.95202671,
        110.69132653],
       [102.9227356 , 106.21264851, 113.5584283 , 107.18989207,
        100.27024654],
       [102.84450329, 111.97742897, 108.87807734, 111.80939261,
        102.9350217 ],
       [104.30788987, 112.82847269, 108.52452995, 109.68992565,
        101.10495125],
       [111.11343812, 112.47299046, 101.57931879, 111.2639754 ,
        105.88920956],
       [109.32853914, 107.89936567, 112.61741521, 107.33164875,
        107.83955408]])

#### Making numpy sequences 

When computing things like functions (in the math sense), we need to start by laying down an x-axis (a working domain of the function). There are two numpy functions, `arange()` and `linspace()` that make this easy for us.

The function `arange()` allows us to specify the endpoints of our domain, and a step size (which defaults to one). We can make a sequence of the numbers one to 10 like this:

In [69]:
my_domain = np.arange(1,11)
print(f'my x axis is: \n {my_domain}')

my x axis is: 
 [ 1  2  3  4  5  6  7  8  9 10]


We can also specify a step size with a third argument. Like this:

In [70]:
my_domain = np.arange(1,11,2)
print(f'my x axis is: \n {my_domain}')

my x axis is: 
 [1 3 5 7 9]


The function `linspace()` is similar, but allows us to specify the number of numbers we need, and it figures out the step size for us. Like this:

In [71]:
my_domain = np.linspace(1,11,10)
print(f'my x axis is: \n {my_domain}')

my x axis is: 
 [ 1.          2.11111111  3.22222222  4.33333333  5.44444444  6.55555556
  7.66666667  8.77777778  9.88888889 11.        ]


If we look at the shape of the object created by either `arange()` or `linspace()`, we see that they are 1D:

In [72]:
my_domain.shape

(10,)

Note that there is only one dimension, so we only need a single index to access a value:

In [73]:
my_domain[3]

4.333333333333334

We can turn this into either a row vector or a column vector by adding a second dimension. Adding a new dimension will make it, technically, a matrix – a matrix with only one column or one row, respectively.

In [74]:
my_domain_row = my_domain[np.newaxis,:]
print(f'my x axis row vector is: \n {my_domain_row}')

my x axis row vector is: 
 [[ 1.          2.11111111  3.22222222  4.33333333  5.44444444  6.55555556
   7.66666667  8.77777778  9.88888889 11.        ]]


This looks the same, but let's check its shape:

In [75]:
my_domain_row.shape

(1, 10)

So now it has 1 row and 10 columns. We therefore use a row *and* a column index to get a value.

In [76]:
my_domain_row[0, 3]

4.333333333333334

---

In the cell below, make a column vector out of `my_domain`, check the shape, and get the third entry.

In [89]:
my_domain_column = my_domain[:, np.newaxis]

print(my_domain_column)
print(f"\nThe shape of the vector is: {my_domain_column.shape}")
print(f"The third entry is: {my_domain_column[2,0]}")

[[ 1.        ]
 [ 2.11111111]
 [ 3.22222222]
 [ 4.33333333]
 [ 5.44444444]
 [ 6.55555556]
 [ 7.66666667]
 [ 8.77777778]
 [ 9.88888889]
 [11.        ]]

The shape of the vector is: (10, 1)
The third entry is: 3.2222222222222223


#### Indexing cells 

Cells and subsets of numpy arrays are accessed – "indexed" – much like Python lists and tuples are.

We've already done a fair amount of indexing, but let's get a bit more flexible. 

#### Indexing rows and columns

We can fetch entire rows or columns using the the colon, `:`. Let's try this on our `my_noise` array. First, let's look at it again:

In [90]:
print(my_noise)

[[ 0.7699664   0.8555334   0.39706116 -0.26035664]
 [-0.51503943 -1.12473421 -1.72812775  1.16831498]
 [-0.60257763  2.09707017  0.01657564  0.30294492]
 [-1.82073614 -1.14801432  0.71877496  0.68474265]]


Now let's get the first column:

In [91]:
my_noise[:,0]

array([ 0.7699664 , -0.51503943, -0.60257763, -1.82073614])

The colon means "everything on this dimension", so the above command means "get all the rows in the first column of `my_noise`.

---

In the cell below, get the second (index = 1) row of data.

In [96]:
second_row = my_noise[1,:]

Now check the shape in the cell below.

In [97]:
second_row.shape

(4,)

Now get the first row and check the shape:

In [99]:
first_row = my_noise[0,:]
first_row.shape

(4,)

Our output in both cases above is a 1D vector. So what do we do if we want to grab a column, say, preserve it as a column? Easy! We just specify a starting and stopping index. Like this:

In [105]:
a_column = my_noise[:,0:1]
a_column

array([[ 0.7699664 ],
       [-0.51503943],
       [-0.60257763],
       [-1.82073614]])

You can see from the output that this is a column, but check its shape in the cell below to be sure:

In [106]:
a_column.shape

(4, 1)

#### Indexing subsets ("slicing")

What we have started doing above is called "slicing", which is carving out ("slicing") subsets of data from an array.

The key to slicing is the colon, `:`, operator. 

Let's play with a 1D vector, `my_domain` first. Let's remind ourselves of it:

In [107]:
print(my_domain)

[ 1.          2.11111111  3.22222222  4.33333333  5.44444444  6.55555556
  7.66666667  8.77777778  9.88888889 11.        ]


If we put a number on either side, we can read as "from the first index to the second index":

In [108]:
my_domain[1:4]

array([2.11111111, 3.22222222, 4.33333333])

If we just put an index on the left, we can read it as "from the index to the end". Like this:

In [109]:
my_domain[2:]

array([ 3.22222222,  4.33333333,  5.44444444,  6.55555556,  7.66666667,
        8.77777778,  9.88888889, 11.        ])

If we just put an index on the right, we can read it as "from the beginning to the index". Like this:

In [110]:
my_domain[:2]

array([1.        , 2.11111111])

---

In the cell below, slice out the 3rd through 5th values of `my_domain`.

In [112]:
my_domain[2:5]

array([3.22222222, 4.33333333, 5.44444444])

---

The extension of slicing to a matrix is straightforward. You just do your slicing on each dimension separately.

Here are some examples of array indexing from Python for Data Analysis by Wes McKinney:

![Array Indexing](images/arrayIndexing.png)

---

In the cell below, try some of these slices on `my_noise`.

In [8]:
my_noise

array([[ 0.02202286,  0.32436108, -1.89779356, -0.4232918 ],
       [ 1.67314474, -1.26653071,  1.35599227, -0.31438775],
       [ 0.32935376,  0.6655817 , -0.11362564,  1.25031778],
       [-1.10465767, -0.6998781 ,  1.05124346,  0.34262669]])

In [7]:
my_noise[:2, 1:] 

array([[ 0.32436108, -1.89779356, -0.4232918 ],
       [-1.26653071,  1.35599227, -0.31438775]])

In [11]:
my_noise[3:, :]

array([[-1.10465767, -0.6998781 ,  1.05124346,  0.34262669]])

In [12]:
my_noise[1:2, :2]

array([[ 1.67314474, -1.26653071]])

#### Summaries of a matrix

A numpy matrix has many methods to compute things about itself, like the sum or mean of its values.

Here's the sum of all the elements of my_noise:

In [13]:
my_noise.sum()

1.1944791153694614

Here's the arithmetic mean:

In [14]:
my_noise.mean()

0.07465494471059134

In the cell below, try `mean(0)` and `mean(1)` – what do these do?

In [22]:
my_noise.mean(0) # calculates mean of columns

array([ 0.22996592, -0.24411651,  0.09895413,  0.21381623])

In [23]:
my_noise.mean(1) # calculates mean of rows

array([-0.49367536,  0.36205464,  0.5329069 , -0.1026664 ])

mean(1) calculates the means of the rows, and mean(0) calculates the means of the columns.

 In the cell below, do a dir(my_noise):

In [18]:
dir(my_noise)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

Now, in the cell below, see if you can use a method of `my_noise` to round all the numbers to the nearest integer:

In [21]:
my_noise.round()

array([[ 0.,  0., -2., -0.],
       [ 2., -1.,  1., -0.],
       [ 0.,  1., -0.,  1.],
       [-1., -1.,  1.,  0.]])